md "Clubes"
cd "Clubes"

md "Serie A"
md "Serie B"

cd "Serie A"
md "Flamengo"
md "Palmeiras"
md "Atletico Mineiro"
md "Gremio"
md "Sao Paulo"
md "Fluminence"
md "Internacional"
md "Santos"
md "Athletico Paranaense"
md "Corinthians"
md "Bragantino"
md "Fortaleza"
md "EC Bahia"
md "Ceara SC"
md "Cuiaba EC"
md "Atletico Goianiense"
md "EC Juventude"
md "America Mineiro"
md "Sport Recife"
md "Chapecoense"

